version: '3.8'

services:
  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APP_NAME=PROJECT_NAME_PLACEHOLDER
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Optional PostgreSQL Database (uncomment if needed)
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: PROJECT_NAME_PLACEHOLDER
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Optional Redis Cache (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# volumes:
#   postgres_data:
#   redis_data: